[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
board_build.f_cpu = 160000000L
upload_speed = 921600
monitor_speed = 115200

lib_deps =
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    h2zero/NimBLE-Arduino @ ^1.4.1

build_flags = 
    -DCORE_DEBUG_LEVEL=0
